---
- name: Start kafka-zookeeper
  systemd:
    name: kafka-zookeeper
    state: started
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"
- name: Start kafka-zookeeper sysvinit
  service:
    name: kafka-zookeeper
    state: started
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "6"

- wait_for:
    host: "0.0.0.0"
    port: 2181
    timeout: 120

- name: Start kafka
  systemd:
    name: kafka
    state: started
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"
- name: Start kafka sysvinit
  service:
    name: kafka
    state: started
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "6"

- wait_for:
    host: "{{ inventory_hostname }}"
    port: 9092
    timeout: 120

- debug:
    msg:
    - "Kafka has been installed"
